
modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId="rotp_an"
version="${file.jarVersion}"
displayName="RotP Aqua Necklace"
logoFile="logo.png"
authors="DanielGamer321, StandoByte"
description='''
An addon for Ripples of the Past mod, adding a new Stand - Aqua Necklace.
'''
[[dependencies.rotp_an]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_an]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_an]]
    modId="jojo"
    mandatory=true
    versionRange="[0.2.2,0.3)"
    ordering="AFTER"
    side="BOTH"
